---
- url: http://localhost:9090
  query_list:
    - node_disk_io_time_seconds_total
    - up
  bearer_token:
  disable_ssl: True
  start_time_list:
  end_time_list:


- url: https://prometheus-k8s-openshift-monitoring.apps.awsovn4312aakarsh.perf-testing.devcluster.openshift.com
  query_list:
    - sum(container_memory_rss{namespace=~"openshift-kube-apiserver",name!="",container=~"kube-apiserver.*"}) by (container)
    - up
  bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ii1tS1piNmhXY2p6UXd3WFVwejJCZlREQ01HeGdzRmhyaTAxcDVhNUlmZ0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uY
    W1lc3BhY2UiOiJvcGVuc2hpZnQta3ViZS1hcGlzZXJ2ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYXBpc2VydmVyLXBwcm9mLXRva2VuLXo0cmJiIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9
    zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFwaXNlcnZlci1wcHJvZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjM5NjdiYmNlLTMzYjQtNDkxNi1iZGQ1LTdhNTk4ZTMyMjRlMSIsInN1YiI6InN5c
    3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuc2hpZnQta3ViZS1hcGlzZXJ2ZXI6YXBpc2VydmVyLXBwcm9mIn0.QoAoGeUuHWMiKVTPe_GQoMVnCRl65-v8Zsc9qiqQ1u_yvtX-X58g4fxNJOf1ervFQsX9MTbqdlKr5IFGOfLQl470ZAZfYQPl1BlzchG
    t-bag1Hj6TXYKEFwLlz8T2UuSVGb0q6TfLlIjRhV5DyPbquzqV6j1w6ByU1dfKn0K9RuvWjGtVIziGs9QYMcEjnJ9IjEjSkV_4mPONTUM7jjc_V2jldx0F-GBQhWYV5qIfdSzvjB8Wi9n6pXkllDHbOdLK0T1SrX5YPyz8wGosn0RNNDbT2cMZoDir
    hSdLVgrGDSG04McpqYcteruZk-_cICNaT1mge70ThOgaQOzPpq5wg
  disable_ssl: True
  start_time_list:
    - 1588791810
    - 1588791710
  end_time_list:
    - 1588795118
    - 1588795018
...
